# Generated by Django 5.2.1 on 2025-05-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='genero',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outro', 'Outro')], default='outro', max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='idade',
            field=models.CharField(choices=[('18-25', '18 a 25'), ('25-40', '25 a 40'), ('40-60', '40 a 60'), ('61+', '61 ou mais')], default='18-25', max_length=10),
        ),
    ]
