# Generated by Django 5.2.1 on 2025-05-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0002_feedback_genero_feedback_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='genero',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outro', 'Outro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='idade',
            field=models.CharField(choices=[('18-25', '18 a 25'), ('25-40', '25 a 40'), ('40-60', '40 a 60'), ('61+', '61 ou mais')], max_length=10),
        ),
    ]
