# Generated by Django 5.2.1 on 2025-06-01 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0003_alter_feedback_genero_alter_feedback_idade'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='numberbus',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='linha',
            field=models.CharField(max_length=50),
        ),
    ]
